# **Numpy Basic Functionalities**

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.20.1


## 1. Creating Numpy Arrays

In [3]:
# np.array
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# 2D and 3D
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
c = np.array([[[1,2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# dtype
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [8]:
# np.arange --> (start, stop(exclusive), step)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# help(np.arange)

In [19]:
# reshape
a1 = np.arange(0, 20)
a2 = a1.reshape(5, 4) # 5*4 = 20

print("a1:", a1)
print(a1.shape)
print()
print("a2:", a2)
print(a2.shape)

a1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)

a2: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)


In [21]:
# np.ones --> ((n, m)) ; (n, m) = dimension
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# np.zeros -- ()
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
# np.random
np.random.random((2, 5))

array([[0.39660127, 0.2777757 , 0.52840912, 0.195231  , 0.11618387],
       [0.8509222 , 0.18993285, 0.47728934, 0.57846105, 0.22496561]])

In [28]:
# np.linspace --> (start, stop(inclusive), no of elements)
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Array Attributes

In [31]:
a1 = np.array([[1, 2],[3, 4]])

In [32]:
# ndim
a1.ndim

2

In [33]:
# shape
a1.shape

(2, 2)

In [34]:
# size --> no of elements
a1.size

4

In [35]:
# itemsize --> every ele is int --> return no of bytes of this dtype
a1.itemsize

4

In [36]:
# dtype
a1.dtype

dtype('int32')

# Changing Data Types

In [40]:
a1.astype('int64')

array([[1, 2],
       [3, 4]], dtype=int64)

# Array Operations